### ISSUE TITLE
Bibliography-3.1.5.zip is missing citation-style-language

### ISSUE THREAD

**Issue by cfeh** [Daniel-KM/Omeka-S-module-Bibliography#1]
Hello!
Bibliography-3.1.5.zip is missing citation-style-language.
I recuperated it now from Bibliography-3.1.0.zip.
Excited to see how it works
Thx
Christoph

**Comment by Daniel-KM** [comment]
This library is not the best one and will be removed in a future release. But for now, I updated the release.
