### ISSUE TITLE
Gitlab warning misleading

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Bibliography#2]
The gitlab warning says 

> support for Omeka S version 3.0 and above are available on GitLab, 

but it seems to be not the case (gitlab hosted module are not compatible with Omeka 3.0).

**Comment by Daniel-KM** [comment]
Oui, je viens juste de finir la mise à jour de la plupart de mes modules pour Omeka v3.

**Comment by pprw** [comment]
Merci pour la mise à jour express (je n'en demandais pas tant  :-) ).

J'ai une erreur à l'installation suite aux derniers commits:

```

Warning: require_once(/home/ahp/sites/test/encyclophilo/omekas_encyclophilo/modules/Bibliography/vendor/autoload.php): failed to open stream: No such file or directory in /home/ahp/sites/test/encyclophilo/omekas_encyclophilo/modules/Bibliography/Module.php on line 30

Fatal error: require_once(): Failed opening required '/home/ahp/sites/test/encyclophilo/omekas_encyclophilo/modules/Bibliography/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ahp/sites/test/encyclophilo/omekas_encyclophilo/modules/Bibliography/Module.php on line 30
```

P-S : Tu préfères que je poste sur gitlab?

**Comment by Daniel-KM** [comment]
Il faut lancer la commande `composer install --no-dev` à la racine du module ou prendre la version zip qui se trouve dans les "livraisons" (releases). 
Pour gitlab, je réponds sur les deux, il est toujours difficile pour les utilisateurs de ne pas dépendre d'un service à tendance monopolistique.

**Comment by pprw** [comment]
> Il faut lancer la commande `composer install --no-dev` à la racine du module ou prendre la version zip qui se trouve dans les "livraisons" (releases).

Mince, j'oublie toujours cette étape. Désolé !

> Pour gitlab, je réponds sur les deux, il est toujours difficile pour les utilisateurs de ne pas dépendre d'un service à tendance monopolistique.

J'essaie à l'avenir d'écrire sur gitlab.
